//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlus.StateMemory {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.10.0.0")]
    internal sealed partial class FolderMemory : global::System.Configuration.ApplicationSettingsBase {
        
        private static FolderMemory defaultInstance = ((FolderMemory)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FolderMemory())));
        
        public static FolderMemory Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSweepIcoFolder {
            get {
                return ((string)(this["lastSweepIcoFolder"]));
            }
            set {
                this["lastSweepIcoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSweepParentDirectory {
            get {
                return ((string)(this["lastSweepParentDirectory"]));
            }
            set {
                this["lastSweepParentDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastTemplateIcoFolder {
            get {
                return ((string)(this["lastTemplateIcoFolder"]));
            }
            set {
                this["lastTemplateIcoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastFileAddFolder {
            get {
                return ((string)(this["lastFileAddFolder"]));
            }
            set {
                this["lastFileAddFolder"] = value;
            }
        }
    }
}
